homeassistant:
  # Name of the location where Home Assistant is running
  name: Maison
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 62
  # metric for Metric, imperial for Imperial
  unit_system: metric
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customglob.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
config:

frontend:
  themes: !include themes.yaml
  javascript_version: latest
  extra_html_url:
    - /local/custom-lovelace/state-card-floorplan.html

lovelace:
  mode: yaml

panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

# Enables a map showing the location of tracked devices
map:
sun:
system_health:
logbook:
# Discover some devices automatically
discovery:
updater:
zeroconf:
mobile_app:
#ios:
person:

# Text to speech
tts:
  - platform: google_translate

# tv
media_player:
  - platform: braviatv
    host: 192.168.1.90

# hue
hue:
  bridges:
    - host: 192.168.1.64

weather:
  - platform: openweathermap
    api_key: !secret weather_api_key

# plex
plex:
  host: 192.168.1.95
  port: 32400
  token: !secret plex_token
  ssl: true
  verify_ssl: false
  media_player:
    show_all_controls: true

# speedtestdotnet
speedtestdotnet:
  scan_interval:
    hours: 3
  monitored_conditions:
    - ping
    - download
    - upload

logger:
  default: info
  logs:
    homeassistant.core: info
    nest.nest: info
    asyncio: info
    homeassistant.components.cloud.iot: info
#    custom_components.arpscan_tracker.device_tracker: debug
#    homeassistant.components.websocket_api: debug

device_tracker:
  - platform: arpscan_tracker
    mac: !secret fabrice_phone_mac
    ip: !secret fabrice_phone_ip
    device_name: igor
    scan_options: --interface=en0 -l -g --retry=2 -b 2
    interval_seconds: 60
    consider_home: 60
    track_new_devices: true

binary_sensor: !include binary_sensors.yaml
alert: !include alerts.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
history: !include history.yaml
notify: !include notifiers.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
recorder: !include recorder.yaml

zwave:
  usb_path: /dev/ttyAMA0
  network_key: "0x80, 0x0D, 0xB7, 0x29, 0x79, 0x5A, 0x1E, 0xFB, 0x9E, 0xFF, 0x8F, 0x03, 0xE0, 0x82, 0x5B, 0x89"