homeassistant:
  # Name of the location where Home Assistant is running
  name: Maison
  # Location required to calculate the time the sun rises and sets
  latitude: 48.812534
  longitude: 2.359192
  elevation: 62
  # metric for Metric, imperial for Imperial
  unit_system: metric
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
config:

frontend:
  themes: !include themes.yaml

# Enables a map showing the location of tracked devices
map:
sun:
system_health:
history:
logbook:
# Discover some devices automatically
discovery:

lovelace:
  mode: yaml

panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave

# Text to speech
tts:
  - platform: google_translate

logger:
  default: info
  logs:
    homeassistant.core: debug
    nest.nest: debug
    asyncio: debug
    homeassistant.components.cloud.iot: debug

input_boolean:
  vacation_mode:
    name: Holiday mode, things are locked or shutdown
    initial: off
    icon: mdi:airplane
  night_mode:
    name: Night mode, the lights do not turn on anymore
    initial: off
    icon: mdi:hotel

notify:
  - platform: smtp
    name: email_notifier
    sender: flasomm@gmail.com
    recipient: flasomm@gmail.com
    sender_name: Home Assistant
    username: flasomm
    password: 4Snn!fA4-L%TU<uC
    port: 25
    debug: true

  - platform: slack
    name: slack_notifier
    api_key: !secret slack_api_key
    default_channel: '#domotique'


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

#device_tracker:
#  - platform: arpscan_tracker
#    mac: 58:e2:8f:20:b0:45
#    ip: 192.168.1.75
#    device_name: marcel
#    scan_options: --interface=en0 -l -g --retry=10 -b 2
#    interval_seconds: 15
#    consider_home: 60
#    track_new_devices: true