homeassistant:
  # Name of the location where Home Assistant is running
  name: Maison
  # Location required to calculate the time the sun rises and sets
  latitude: 48.812534
  longitude: 2.359192
  elevation: 62
  # metric for Metric, imperial for Imperial
  unit_system: metric
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customglob.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
config:

frontend:
  themes: !include themes.yaml
  javascript_version: latest

lovelace:
  mode: yaml

panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave

# Enables a map showing the location of tracked devices
map:
sun:
system_health:
logbook:
# Discover some devices automatically
discovery:
updater:
zeroconf:
mobile_app:
ios:
person:

# Text to speech
tts:
  - platform: google_translate

logger:
  default: info
  logs:
    homeassistant.core: debug
    nest.nest: debug
    asyncio: debug
    homeassistant.components.cloud.iot: debug

device_tracker:
  - platform: arpscan_tracker
    mac: 58:e2:8f:20:b0:45
    ip: 192.168.1.75
    device_name: marcel
    scan_options: --interface=en0 -l -g --retry=2 -b 2
    interval_seconds: 60
    consider_home: 60
    track_new_devices: true

binary_sensor: !include binary_sensors.yaml
alert: !include alerts.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
history: !include history.yaml
notify: !include notifiers.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

zwave:
  usb_path: /dev/ttyAMA0
  network_key: "0x80, 0x0D, 0xB7, 0x29, 0x79, 0x5A, 0x1E, 0xFB, 0x9E, 0xFF, 0x8F, 0x03, 0xE0, 0x82, 0x5B, 0x89"