- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use
    - type: swap_use_percent
    - type: processor_use
    - type: last_boot

- platform: template
  sensors:
    fabrice_at_home:
      friendly_name: Statut
      value_template: '{{ states.device_tracker.marcel.state }}'
      icon_template: >
        {% if is_state('device_tracker.marcel', 'home') %}
          mdi:home
        {% else %}
          mdi:exit-run
        {% endif %}

- platform: synologydsm
  host: 192.168.1.22
  username: !secret synology_user
  password: !secret synology_password
  monitored_conditions:
    - cpu_total_load
    - cpu_system_load
    - memory_size
    - memory_cached
    - memory_real_usage
    - memory_available_swap
    - disk_name
    - network_up
    - volume_percentage_used
    - volume_disk_temp_avg
    - volume_disk_temp_max