- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use
    - type: swap_use_percent
    - type: processor_use
    - type: last_boot

- platform: template
  sensors:
    fabrice_at_home:
      friendly_name: Statut
      value_template: '{{ states.device_tracker.sm_g973f_2.state }}'
      icon_template: >
        {% if is_state('device_tracker.galaxy_s10_2', 'home') or is_state('device_tracker.igor', 'home') or is_state('device_tracker.sm_g973f', 'home') or is_state('device_tracker.sm_g973f_2', 'home')%}
          mdi:home
        {% else %}
          mdi:exit-run
        {% endif %}
    fabrice_phone_battery:
      friendly_name: Statut
      value_template: '{{ state_attr("device_tracker.sm_g973f_2", "battery_level") }}%'
      icon_template: >
        {% if is_state_attr("device_tracker.galaxy_s10_2", "battery_level", 100) or is_state_attr("device_tracker.sm_g973f", "battery_level", 100) or is_state_attr("device_tracker.sm_g973f_2", "battery_level", 100) %}
          mdi:battery
        {% else %}
          mdi:battery-60
        {% endif %}
    temperature_salon:
      friendly_name: Capteur Température Salon
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature_5.state }}'
    temperature_cuisine:
      friendly_name: Capteur Température Cuisine
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature_7.state }}'
    temperature_entree:
      friendly_name: Capteur Température Entree
      value_template: '{{ states.sensor.philio_technology_corp_pst02_c_door_window_3_in_1_sensor_temperature.state }}'
    temperature_mezzanine:
      friendly_name: Capteur Température Mezzanine
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature_3.state }}'
    temperature_sdb:
      friendly_name: Capteur Température SDB
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature_2.state }}'
    temperature_wc:
      friendly_name: Capteur Température WC
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature.state }}'
    temperature_bureau:
      friendly_name: Capteur Température Bureau
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature_6.state }}'
    temperature_chambre:
      friendly_name: Capteur Température Chambre
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature_4.state }}'
    temperature_detecteur_fumee:
      friendly_name: Capteur Température Détecteur Fumée
      value_template: '{{ states.sensor.detecteur_de_fumee_temperature.state }}'
    lumiere_salon:
      friendly_name: Capteur Lumière Salon
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance_5.state }}'
    lumiere_cuisine:
      friendly_name: Capteur Lumière Cuisine
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance_7.state }}'
    lumiere_entree:
      friendly_name: Capteur Lumière Porte Entrée
      value_template: '{{ states.sensor.philio_technology_corp_pst02_c_door_window_3_in_1_sensor_luminance.state }}'
    lumiere_mezzanine:
      friendly_name: Capteur Lumière Mezzanine
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance_3.state }}'
    lumiere_sdb:
      friendly_name: Capteur Lumière SDB
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance_2.state }}'
    lumiere_wc:
      friendly_name: Capteur Lumière WC
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance.state }}'
    lumiere_bureau:
      friendly_name: Capteur Lumière Bureau
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance_6.state }}'
    lumiere_chambre:
      friendly_name: Capteur Lumière Chambre
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance_4.state }}'
    floorplan_date:
      friendly_name: Date
      value_template: '{{now().strftime("%d")}}/{{now().strftime("%m")}}/{{now().strftime("%Y")}}'
    floorplan_full_date:
      friendly_name: Full Date
      value_template: '{{now().strftime("%A")}} {{now().strftime("%d")}} {{now().strftime("%B")}} {{now().strftime("%Y")}}'
    floorplan_time:
      friendly_name: Time
      value_template: '{{now().strftime("%-I")}}:{{now().strftime("%M")}} {{now().strftime("%p")}}'

- platform: synologydsm
  host: 192.168.1.95
  port: 6601
  username: !secret synology_user
  password: !secret synology_password
  monitored_conditions:
    - cpu_total_load
    - cpu_system_load
    - cpu_user_load
    - cpu_other_load
    - memory_size
    - memory_cached
    - memory_real_usage
    - memory_available_swap
    - memory_total_swap
    - memory_total_real
    - network_up
    - network_down
    - disk_name
    - disk_device
    - disk_smart_status
    - disk_status
    - volume_status
    - volume_device_type
    - volume_size_total
    - volume_size_used
    - volume_percentage_used
    - volume_disk_temp_avg
    - volume_disk_temp_max

- platform: plex
  host: 192.168.1.95
  username: !secret plex_user
  password: !secret plex_password
