- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use
    - type: swap_use_percent
    - type: processor_use
    - type: last_boot

- platform: template
  sensors:
    fabrice_at_home:
      friendly_name: Statut
      value_template: '{{ states.device_tracker.marcel.state }}'
      icon_template: >
        {% if is_state('device_tracker.marcel', 'home') %}
          mdi:home
        {% else %}
          mdi:exit-run
        {% endif %}
    temperature_salon:
      friendly_name: Capteur Température Salon
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature_3.state }}'
    lumiere_salon:
      friendly_name: Capteur Lumière Salon
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance_3.state }}'
    temperature_cuisine:
      friendly_name: Capteur Température Cuisine
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature_2.state }}'
    lumiere_cuisine:
      friendly_name: Capteur Lumière Cuisine
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance_2.state }}'
    temperature_entree:
      friendly_name: Capteur Température Entree
      value_template: '{{ states.sensor.philio_technology_corp_pst02_c_door_window_3_in_1_sensor_temperature.state }}'
    porte_entree:
      friendly_name: Capteur Porte Entrée
      value_template: '{{ states.binary_sensor.philio_technology_corp_pst02_c_door_window_3_in_1_sensor_sensor.state }}'
    lumiere_entree:
      friendly_name: Capteur Lumière Porte Entrée
      value_template: '{{ states.sensor.philio_technology_corp_pst02_c_door_window_3_in_1_sensor_luminance.state }}'
    temperature_mezzanine:
      friendly_name: Capteur Température Mezzanine
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature_4.state }}'
    lumiere_mezzanine:
      friendly_name: Capteur Lumière Mezzanine
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance_4.state }}'
    temperature_sdb:
      friendly_name: Capteur Température SDB
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature_5.state }}'
    lumiere_sdb:
      friendly_name: Capteur Lumière SDB
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance_5.state }}'
    temperature_wc:
      friendly_name: Capteur Température WC
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature_6.state }}'
    lumiere_wc:
      friendly_name: Capteur Lumière WC
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance_6.state }}'
    lumiere_bureau:
      friendly_name: Capteur Lumière Bureau
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance.state }}'
    temperature_bureau:
      friendly_name: Capteur Température Bureau
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature.state }}'
    temperature_chambre:
      friendly_name: Capteur Température Chambre
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature_7.state }}'
    lumiere_chambre:
      friendly_name: Capteur Lumière Chambre
      value_template: '{{ states.sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance_7.state }}'
    temperature_detecteur_fumee:
      friendly_name: Capteur Température Détecteur Fumée
      value_template: '{{ states.sensor.fibaro_system_fgsd002_smoke_sensor_temperature.state }}'

- platform: synologydsm
  host: 192.168.1.22
  username: !secret synology_user
  password: !secret synology_password
  monitored_conditions:
    - cpu_total_load
    - cpu_system_load
    - memory_size
    - memory_cached
    - memory_real_usage
    - memory_available_swap
    - disk_name
    - network_up
    - volume_percentage_used
    - volume_disk_temp_avg
    - volume_disk_temp_max