title: Dashboard

resources:
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.102.3
    type: module
  - url: /local/custom-lovelace/card-tools/card-tools.js?v=0.102.3
    type: js
  - url: /local/custom-lovelace/vertical-stack-in-card/vertical-stack-in-card.js?v=0.102.3
    type: js
  - url: /local/custom-lovelace/auto-entities/auto-entities.js?v=0.102.3
    type: js
  - url: /local/custom-lovelace/bar-card/bar-card.js?v=0.102.3
    type: js

views:
  - !include lovelace/view_home.yaml
  - !include lovelace/view_radiators.yaml
  - !include lovelace/view_medias.yaml
  - !include lovelace/view_alarms.yaml
  - !include lovelace/view_system.yaml
